name: fooderlich
description: a social recipe app to keep track of new dishes, and share with friends.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.1 
  provider: ^6.0.5
  flutter_colorpicker: ^1.0.3
  intl: ^0.18.0
  uuid: ^3.0.7
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.8
  shared_preferences: ^2.0.15
  go_router: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/sample_data/
    - assets/profile_pics/
    - assets/fooderlich_assets/
